# Generated by Django 2.2.4 on 2019-08-21 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('citizen_id', models.PositiveIntegerField(db_index=True)),
                ('town', models.CharField(max_length=512)),
                ('street', models.CharField(max_length=512)),
                ('building', models.CharField(max_length=512)),
                ('apartment', models.PositiveIntegerField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CitizenRelations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_citizen_id', models.IntegerField(db_index=True)),
                ('from_citizen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_1', to='imports.Citizen')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='data_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='citizens', to='imports.Import'),
        ),
        migrations.AlterUniqueTogether(
            name='citizen',
            unique_together={('citizen_id', 'data_import')},
        ),
    ]
